basic_settings:
  site_title: Garritt J. Gala
  site_tagline: Welcome to my Blog!
  favicon_image: /images/favicon.ico

header_settings:
  logo_image: 
  logo_width: 200
  overlay_opacity: 0.7

menu_settings:
  menu_items:
    - title: 'Blog'
      url: '/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'Photography'
      url: '/photos/'
    - title: 'About'
      url: '/about'
    - title: 'Contact'
      url: '/contact'

grid_settings:
  grid_spacing: 10

contact_settings:
  form_action: 'https://formspree.io/blog@garrittgala.com'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: ''
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: 'https://github.com/gjgala'
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''

color_settings:
  background_color: '#080C12'
  background_alt_color: '#2F2F2F'
  text_dark_color: '#E0E0E0'
  text_medium_color: '#F0F0F0'
  text_light_color: '#FCFCFC'
  accent_color: '#DBFCCA'
  border_color: '#999999'
  overlay_background_color: '#161B21'
  overlay_text_color: '#E0E0E0'
  error_color: '#D64541'

font_settings:
  font_embed: '<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">'
  title_font: '"Merriweather", sans-serif'
  body_font: '"Muli", sans-serif'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 400
    letter_spacing: 0
  site_tagline:
    small_size: 16
    medium_size: 17
    large_size: 18
    weight: 400
    letter_spacing: 0
    line_height: 1.5
  menu:
    small_size: 30
    medium_size: 17
    large_size: 18
    weight: 400
    letter_spacing: 0
  h1:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 400
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 400
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 400
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 400
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""
